### ISSUE TITLE
fullcalendar adjustments - make it working correctly on mobile

### ISSUE THREAD

**Issue by bszymik** [ibo549/calWebApp#11]
make it working correctly on mobile (Internet Explorer WP, FireFox mobile etc) - focus on clicking/selecting appointment, scrolling calendar with select mode etc.

**Comment by ibo549** [comment]
Maybe we can try a different approach. 
It seems like, in JavaScript it's possible to get if a browser has a touch capability.
See the stackoverflow discussion [here](http://stackoverflow.com/questions/4817029/whats-the-best-way-to-detect-a-touch-screen-device-using-javascript#).

If it's a touch screen device - we can completely turn off the current multi select mode. So that user is only able to select one event slot or all day event. Or maybe we can provide a completely different multi-select for touch devices.

If it's a device without touch capability, we can use the current version.

**Comment by ibo549** [comment]
Also, maybe instead of click/select, there is a third option - such as 'tap' or 'touch' that can be used in touch devices.
