### ISSUE TITLE
Adding appointment

### ISSUE THREAD

**Issue by ibo549** [ibo549/calWebApp#4]
When user taps on an appointment, open a bootstrap modal dialog:
- On top center: 'Unavailable'
- Patient Name
- Phone Number
- Patient Note

If 'Unavailable' is selected, than all the other patient related controls should disappear and a reason box should appear.

**Comment by ibo549** [comment]
Just to let you know that relevant properties for appointments on the API are added and deployed live, 
appointments now have: 
bool IsAvailable
string AppointmentNote
https://github.com/ibo549/calREST/issues/12

**Comment by ibo549** [comment]
Lately I was thinking that, with the introduction of Appointment Notes field - we should re-think about the UX of adding an appointment because now we have two 'note' fields. One for patients, another for appointments. 
Indeed when displaying an appointment on the calendar view - we definitely gonna display the name of the patient, this part is clear.  

The unclear part is, where the 'patient note' field should become addable/editable and viewable.
In my opinion the more important note to be added when an appointment is being added, is the note of the appointment but not the note of the patient. The note of the patient should be shown/edited/added only through the patient view. A user should be able to reach a patient view either through patient search or through the appointment itself by clicking the patient name. The reason behind is that, that in the very first addition of a patient, usually the user would not have too much opinion about the patient. But rather may want to express opinion about that particular appointment itself.
Looking forward to hear your thoughts.

**Comment by bszymik** [comment]
The real question that pops into my mind now is: do we really need 2 note fields?
From data logic and structure currently we need - because WE are distinguishing appointment notes and patient notes from each other, but in my opinion it will complicate the user experience.
User while adding an appointment won't need to distinguish is the note that he want's to add is a patient note or appointment note or maybe both and than he needs to fill both fields. I suggest that we should create new model - Note - which might be related with patient or appointment or both - and thanks to this later ffor each patient in some patient view we will be able to display all the notes related with patient and his/her appointments.
Will it introduce any problems? - don't know yet ;)
